functional:
  - Регистрация пользоваталея 
  - Вход в систему при помощи сторонних акканутов (Git hub)
  - Авторизация 
  - Создать игру 
  - Сайт должен быть удобным на мобильном устройстве
  - Пригласить друга в игру
  - Просмотр своего профиля
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Локализация 
implicit:
  - Общедоступность ( Требования к общедоступности в контексте удобства использования для людей с ограниченными возможностями)
  - Стабильность
